name: Run Python App

on:
  push:
    branches:
      - main   # Run when changes are pushed to the main branch
  pull_request:
    branches:
      - main   # Run for pull requests targeting the main branch

jobs:
  run-python-app:
    runs-on: ubuntu-latest   # You can choose another runner like macos-latest or windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   # This step checks out your repository to the runner

      - name: Set up Python
        uses: actions/setup-python@v4   # This sets up Python
        with:
          python-version: '3.8'   # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # Assuming you have a requirements.txt file for dependencies

      - name: Run app.py
        run: python app.py   # Run your Python app script
